spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/news?&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 654321
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
  thymeleaf:
    mode: HTML
  profiles:
    active: dev