spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssmt?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 654321
  thymeleaf:
    mode: HTML
  profiles:
    active: dev